COUCHDB_ROOT = ..
include $(COUCHDB_ROOT)/Makefile.bootstrap
include $(COUCHDB_MAKED)/core
include $(COUCHDB_MAKED)/metadocs
include $(COUCHDB_MAKED)/build-targets
include Makefile.depends

BASE_DOCUMENT = couchdb-manual
BASE_VERSION  = 1.1
EPUB_ICON = images/epub-icon.png
