COUCHDB_ROOT = ../../..
include $(COUCHDB_ROOT)/Makefile.bootstrap
include $(COUCHDB_MAKED)/core
include $(COUCHDB_MAKED)/metadocs
include $(COUCHDB_MAKED)/build-targets

METATYPE = json
XMLFORMAT_CONF = $(COUCHDB_BIN)/xmlformat-json.conf
