COUCHDB_ROOT = ../../..
include $(COUCHDB_ROOT)/Makefile.bootstrap
include $(COUCHDB_MAKED)/core
include $(COUCHDB_MAKED)/metadocs
include $(COUCHDB_MAKED)/build-targets

METATYPE = urlapi
XMLFORMAT_CONF = $(COUCHDB_BIN)/xmlformat-urlapi.conf
